package ar.edu.utn.frc.tup.p4.apigateway.integration;

import ar.edu.utn.frc.tup.p4.apigateway.constants.IdentityHeaders;
import ar.edu.utn.frc.tup.p4.apigateway.filters.CorrelationIdFilter;
import ar.edu.utn.frc.tup.p4.apigateway.filters.LoggingFilter;
import ar.edu.utn.frc.tup.p4.apigateway.security.CookieOrHeaderBearerConverter;
import ar.edu.utn.frc.tup.p4.apigateway.support.AbstractGatewayTest;
import ar.edu.utn.frc.tup.p4.apigateway.support.TokenFactory;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.ReactiveStringRedisTemplate;

import java.util.Map;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * DoD criterion 9: a request can be followed end to end across the Gateway and
 * a microservice logs WITH A SINGLE ID.
 *
 * The criterion said "inspection of logback-spring.xml + assert on the
 * appender". Inspecting the XML was not enough: the pattern had `%X{requestId}`
 * and it was perfect, the filter published the id in the Reactor context and
 * that was perfect too, and the field still came out empty because `%X` reads
 * the MDC and nobody wrote there. A criterion verified by reading a config file
 * does not test behaviour.
 *
 * This test asserts on the MDC of the real log event, generated by a request
 * that went through the complete pipeline over HTTP.
 */
class CorrelationInLogsIT extends AbstractGatewayTest {

    @Autowired ReactiveStringRedisTemplate redis;

    private ListAppender<ILoggingEvent> captured;

    @BeforeEach
    void attachAppender() {
        captured = new ListAppender<>();
        captured.start();
        ((Logger) LoggerFactory.getLogger(LoggingFilter.class)).addAppender(captured);
    }

    @AfterEach
    void detachAppender() {
        ((Logger) LoggerFactory.getLogger(LoggingFilter.class)).detachAppender(captured);
    }

    @Test
    @Timeout(value = 30, unit = TimeUnit.SECONDS)
    void the_incoming_requestId_appears_in_the_MDC_of_the_log_line() {
        UUID user = UUID.randomUUID();
        seedSession(redis, user, "sid-1");
        String mine = "rid-" + UUID.randomUUID();

        client.get().uri("/api/users/me")
                .cookie(CookieOrHeaderBearerConverter.ACCESS_COOKIE, TokenFactory.person(user, "sid-1"))
                .header(IdentityHeaders.REQUEST_ID, mine)
                .exchange()
                .expectStatus().isOk()
                // It comes back in the response: it is the id a person can report.
                .expectHeader().valueEquals(IdentityHeaders.REQUEST_ID, mine);

        assertThat(captured.list)
                .describedAs("LoggingFilter must have logged the request")
                .isNotEmpty();

        assertThat(captured.list)
                .describedAs("every line of the request carries ITS requestId in the MDC")
                .anySatisfy(event -> assertThat(
                        event.getMDCPropertyMap().get(CorrelationIdFilter.CTX_REQUEST_ID))
                        .isEqualTo(mine));
    }

    @Test
    @Timeout(value = 30, unit = TimeUnit.SECONDS)
    void without_an_incoming_header_the_MDC_still_carries_the_generated_id() {
        // Most requests arrive without `X-Request-Id`: the Gateway generates it.
        // If the bridge only worked with the incoming header, the log would be
        // empty right in the common case.
        UUID user = UUID.randomUUID();
        seedSession(redis, user, "sid-1");

        var response = client.get().uri("/api/users/me")
                .cookie(CookieOrHeaderBearerConverter.ACCESS_COOKIE, TokenFactory.person(user, "sid-1"))
                .exchange()
                .expectStatus().isOk()
                .expectHeader().exists(IdentityHeaders.REQUEST_ID)
                .returnResult(String.class);

        String generated = response.getResponseHeaders().getFirst(IdentityHeaders.REQUEST_ID);

        assertThat(captured.list)
                .describedAs("the MDC id is the SAME one that came back to the client")
                .anySatisfy(event -> assertThat(
                        event.getMDCPropertyMap().get(CorrelationIdFilter.CTX_REQUEST_ID))
                        .isEqualTo(generated));
    }

    @Test
    @Timeout(value = 30, unit = TimeUnit.SECONDS)
    void the_traceId_of_the_incoming_traceparent_appears_in_the_MDC_of_the_log_line() {
        // W3C Trace Context: the Gateway preserves the incoming traceparent and
        // derives traceId/spanId from it. They are the SAME values that travel
        // to the destination and that users-service prints, so the Gateway line
        // can be crossed with the microservice's (DoD criterion 9).
        UUID user = UUID.randomUUID();
        seedSession(redis, user, "sid-1");
        String traceparent = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";

        client.get().uri("/api/users/me")
                .cookie(CookieOrHeaderBearerConverter.ACCESS_COOKIE, TokenFactory.person(user, "sid-1"))
                .header("traceparent", traceparent)
                .exchange()
                .expectStatus().isOk();

        assertThat(captured.list)
                .describedAs("the traceId of the incoming traceparent must come out in the MDC")
                .anySatisfy(event -> {
                    Map<String, String> mdc = event.getMDCPropertyMap();
                    assertThat(mdc).containsEntry(
                            CorrelationIdFilter.CTX_TRACE_ID, "4bf92f3577b34da6a3ce929d0e0e4736");
                    assertThat(mdc).containsEntry(
                            CorrelationIdFilter.CTX_SPAN_ID, "00f067aa0ba902b7");
                });
    }

    @Test
    @Timeout(value = 30, unit = TimeUnit.SECONDS)
    void without_an_incoming_traceparent_the_MDC_still_carries_a_generated_traceId() {
        // The common case: the Gateway generates the traceparent. The log has to
        // show that traceId/spanId even if none arrived.
        UUID user = UUID.randomUUID();
        seedSession(redis, user, "sid-1");

        client.get().uri("/api/users/me")
                .cookie(CookieOrHeaderBearerConverter.ACCESS_COOKIE, TokenFactory.person(user, "sid-1"))
                .exchange()
                .expectStatus().isOk();

        assertThat(captured.list)
                .describedAs("every line of the request carries a valid traceId generated by the Gateway")
                .anySatisfy(event -> {
                    Map<String, String> mdc = event.getMDCPropertyMap();
                    assertThat(mdc).containsKey(CorrelationIdFilter.CTX_TRACE_ID);
                    assertThat(mdc.get(CorrelationIdFilter.CTX_TRACE_ID)).matches("[0-9a-f]{32}");
                    assertThat(mdc.get(CorrelationIdFilter.CTX_SPAN_ID)).matches("[0-9a-f]{16}");
                });
    }
}
