package ar.edu.utn.frc.tup.p4.apigateway.support;

import com.redis.testcontainers.RedisContainer;
import org.springframework.data.redis.core.ReactiveStringRedisTemplate;
import okhttp3.mockwebserver.Dispatcher;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;
import org.testcontainers.utility.DockerImageName;

import java.io.IOException;
import java.time.Duration;
import java.util.concurrent.TimeUnit;

/**
 * Base for the integration tests. It brings up:
 *  - a MockWebServer serving the JWKS with TokenFactory's key;
 *  - a MockWebServer acting as the destination microservice and RECORDING
 *    what it receives, so assertions can be made on the injected headers;
 *  - real Redis, because the single session and the fail-mode of DEC-01
 *    cannot be simulated with a mock without losing exactly what is meant to
 *    be tested.
 *
 * SINGLETON PATTERN, deliberate: the three resources are started ONCE for the
 * whole JVM and are not shut down when each class finishes.
 *
 * With @Testcontainers + @Container, JUnit shuts the container down when the
 * class ends and brings it back on ANOTHER PORT for the next one — but Spring
 * CACHES the context between classes, so the reused context keeps pointing at
 * the old port and everything fails with RedisCommandTimeoutException. The
 * tests pass one by one and fail all together: the most confusing symptom
 * possible.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public abstract class AbstractGatewayTest {

    protected static final RedisContainer REDIS;
    protected static final MockWebServer JWKS;
    protected static final MockWebServer DESTINATION;

    static {
        REDIS = new RedisContainer(DockerImageName.parse("redis:7-alpine"));
        REDIS.start();

        JWKS = new MockWebServer();
        JWKS.setDispatcher(new Dispatcher() {
            @Override
            public MockResponse dispatch(RecordedRequest req) {
                return new MockResponse()
                        .setHeader("Content-Type", "application/json")
                        .setBody(TokenFactory.jwksJson());
            }
        });

        DESTINATION = new MockWebServer();
        DESTINATION.setDispatcher(new Dispatcher() {
            @Override
            public MockResponse dispatch(RecordedRequest req) {
                return new MockResponse().setResponseCode(200).setBody("ok");
            }
        });

        try {
            JWKS.start();
            DESTINATION.start();
        } catch (IOException e) {
            throw new IllegalStateException("Could not start the MockWebServer instances", e);
        }
        // They are never stopped: they live as long as the JVM does. Ryuk cleans them up.
    }

    @LocalServerPort
    protected int port;

    protected WebTestClient client;

    /**
     * Built by hand against the real port instead of injecting the bean: that
     * makes it explicit that the requests go through the COMPLETE pipeline
     * over HTTP, not a mock of the context. The long timeout is for the
     * resilience tests, which provoke slow destinations on purpose.
     */
    @BeforeEach
    void buildClient() throws InterruptedException {
        client = WebTestClient.bindToServer()
                .baseUrl("http://localhost:" + port)
                .responseTimeout(Duration.ofSeconds(30))
                .build();

        // The MockWebServer is a JVM singleton, so its request queue is
        // SHARED between test classes. Without draining it, a takeRequest()
        // returns the request another test left and the assertion measures
        // something else. Draining it in each test is what makes the
        // execution order irrelevant.
        while (DESTINATION.takeRequest(1, TimeUnit.MILLISECONDS) != null) {
            // drain
        }
    }

    @DynamicPropertySource
    static void properties(DynamicPropertyRegistry r) {
        r.add("spring.data.redis.host", REDIS::getHost);
        r.add("spring.data.redis.port", () -> REDIS.getMappedPort(6379));

        r.add("spring.security.oauth2.resourceserver.jwt.jwk-set-uri",
                () -> JWKS.url("/.well-known/jwks.json").toString());

        // SIMPLE DISCOVERY, not static routes. The routes are generated by
        // the production AllowlistRouteLocator from the allowlist, and the
        // load balancer resolves lb://{serviceId} against these instances.
        //
        // Before this they were static routes pointing directly at the
        // MockWebServer. It looked simpler and it was a lie: it left UNTESTED
        // the route generation, which is where the SpEL locator bug was — the
        // Gateway came up with an empty table and answered 404 to everything,
        // with all 101 tests green. A test that replaces the mechanism it
        // claims to test tests nothing.
        //
        // On the way, with uri lb://users-service the ServiceAudienceFilter
        // resolves the destination by the route's HOST, which is the branch
        // that runs in production; with http://localhost:PORT it always fell
        // into the derivation by path, i.e. it tested the fallback branch.
        String destinationUri = "http://localhost:" + DESTINATION.getPort();

        r.add("spring.cloud.discovery.client.simple.instances.users-service[0].uri",
                () -> destinationUri);
        // A foreign micro, so AccountStateGuardIT and ServiceAudienceIT can
        // test the coarse gate and the audience bounded to another
        // destination.
        r.add("spring.cloud.discovery.client.simple.instances.cursos-service[0].uri",
                () -> destinationUri);
        r.add("gateway.routing.allowlist", () -> "users-service,cursos-service");

        // No Eureka: the simple discovery suffices, it needs no server.
        r.add("eureka.client.enabled", () -> "false");
    }

    /**
     * Consumes and returns the last request that arrived at the destination.
     *
     * With a timeout, and NEVER without it: `takeRequest()` without arguments
     * waits forever. If the request does not reach the destination -- because
     * a filter rejected it before routing, which is this pipeline's most
     * common bug -- the test does not fail: it HANGS the whole run, with not
     * a single line explaining why. It happened once and ate forty minutes
     * until someone looked at a jstack.
     *
     * The timeout failure says the only thing there is to know: the request
     * did not arrive, so someone in the chain answered before routing.
     */
    protected RecordedRequest lastRequestToDestination() throws InterruptedException {
        RecordedRequest received = DESTINATION.takeRequest(10, TimeUnit.SECONDS);
        if (received == null) {
            throw new AssertionError(
                    "The request did not reach the destination within 10s: some filter in the "
                    + "chain rejected it before routing. Check the response status.");
        }
        return received;
    }

    // -----------------------------------------------------------------------
    // Session in Redis
    //
    // The key format is NOT the Gateway's: it is written by users-service's
    // login (DEC-22) and the Gateway only reads it. It lives here, in one
    // single place, because at least eight ITs spread across four batches
    // need it: if each one built it by hand, it would be enough for someone
    // to write `sessions:` in plural for its test to pass green testing
    // nothing.
    //
    // The `sid` must be THE SAME as the token's `sid` claim, or SessionGuard
    // rejects it with session-superseded, which is exactly what these tests
    // are not testing.
    // -----------------------------------------------------------------------

    /** The exact key that users-service writes. */
    protected static String sessionKey(Object userId) {
        return "session:" + userId;
    }

    /** Makes `userId`'s session CURRENT with that `sid`. */
    protected void seedSession(ReactiveStringRedisTemplate redis, Object userId, String sid) {
        redis.opsForValue().set(sessionKey(userId), sid).block();
    }

    /** Deletes the session: that is what a logout does, and the 401 that follows is DEC-22. */
    protected void clearSession(ReactiveStringRedisTemplate redis, Object userId) {
        redis.delete(sessionKey(userId)).block();
    }
}
